language: node_js

node_js:
  - 9
  - 8

os:
  - linux
  - osx

notifications:
  webhooks: https://app.fossa.io/hooks/travisci

# before_script:
#   - npm prune
#   - npm dedupe

script:
  - npm test

after_script:
  # - 'cat ./lib/__tests__/coverage/lcov.info | coveralls'
  - 'cat ./lib/__tests__/coverage/lcov.info | codacy-coverage'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
