language: node_js

node_js:
  - 9
  - 8

os:
  - linux
  - osx

notifications:
  webhooks: https://app.fossa.io/hooks/travisci

git:
  depth: 1

before_script:
   - npm dedupe
#   - npm prune

script:
  - npm test

after_script:
  - npm run posttest:ci:coverage:codacy
  # - cat $TRAVIS_BUILD_DIR/lib/__tests__/coverage/lcov.info | codacy-coverage --token $CODACY_PROJECT_TOKEN
  # - 'cat ./lib/__tests__/coverage/lcov.info | coveralls'
  # - 'cat ./lib/__tests__/coverage/lcov.info | codacy-coverage'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx travis-deploy-once "npx semantic-release"
